### ISSUE TITLE
how to export the model

### ISSUE THREAD

**Issue by ghtwht** [bytedance/neurst#41]
How to export model with the format used by lightseq and tortion?

**Comment by godweiyang** [comment]
You can export the models trained by neurst using the scripts in [https://github.com/godweiyang/chatbot/tree/master/export](https://github.com/godweiyang/chatbot/tree/master/export).

The following is the export command:
```shell
python3 export.py \
    --model_dir models \
    --output_file model.pb \
    --generation_method topk \
    --topk 4 \
    --length_penalty 0.6 \
    --beam_size 4
```

**Comment by kaierlong** [comment]
@godweiyang 
Hi, when I use your scripts to export model, there are some errors：
```shell
Traceback (most recent call last):
  File "export.py", line 161, in <module>
    app.run(_main, argv=["pseudo.py"])
  File "/mnt/data_0301_12t/xingchaolong/home/pyenvs/env_neurst_lightseq/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/mnt/data_0301_12t/xingchaolong/home/pyenvs/env_neurst_lightseq/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "export.py", line 154, in _main
    export_lightseq_model(
  File "export.py", line 127, in export_lightseq_model
    transfer_ckpt2pb(
  File "/mnt/data_0301_12t/xingchaolong/home/codes/trans/neurst/demo/export/transformer_proto_utils.py", line 256, in transfer_ckpt2pb
    _fill_layer(
  File "/mnt/data_0301_12t/xingchaolong/home/codes/trans/neurst/demo/export/transformer_proto_utils.py", line 139, in _fill_layer
    assert len(tmp) == 1
AssertionError
```

the cmd as below
```shell
python3 export.py --model_dir ../wmt14_en_de/benchmark_base/ --output_file ../infer/model.pb --beam_size 4 --length_penalty 0.6
```

and the model is `transformer_base`.

Any help for this？

**Comment by godweiyang** [comment]
> @godweiyang Hi, when I use your scripts to export model, there are some errors：
> 
> ```shell
> Traceback (most recent call last):
>   File "export.py", line 161, in <module>
>     app.run(_main, argv=["pseudo.py"])
>   File "/mnt/data_0301_12t/xingchaolong/home/pyenvs/env_neurst_lightseq/lib/python3.8/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "/mnt/data_0301_12t/xingchaolong/home/pyenvs/env_neurst_lightseq/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "export.py", line 154, in _main
>     export_lightseq_model(
>   File "export.py", line 127, in export_lightseq_model
>     transfer_ckpt2pb(
>   File "/mnt/data_0301_12t/xingchaolong/home/codes/trans/neurst/demo/export/transformer_proto_utils.py", line 256, in transfer_ckpt2pb
>     _fill_layer(
>   File "/mnt/data_0301_12t/xingchaolong/home/codes/trans/neurst/demo/export/transformer_proto_utils.py", line 139, in _fill_layer
>     assert len(tmp) == 1
> AssertionError
> ```
> 
> the cmd as below
> 
> ```shell
> python3 export.py --model_dir ../wmt14_en_de/benchmark_base/ --output_file ../infer/model.pb --beam_size 4 --length_penalty 0.6
> ```
> 
> and the model is `transformer_base`.
> 
> Any help for this？

Can you provide your trainning command and neurst version?

**Comment by kaierlong** [comment]
@godweiyang 
The neurst version is `0.1.0`, but I installed it from source use the following command:

```shell
git clone -b lightseq https://github.com/bytedance/neurst.git
cd neurst/
pip3 install -e .
pip3 install lightseq-tf2.4.1-cuda11.0.221==2.0.1
pip3 install absl-py
pip3 install tensorflow==2.4.1
```

- And the training command is:
```shell
python3 -m neurst.cli.run_exp --config_paths wmt14_en_de/training_args.yml,wmt14_en_de/translation_bpe.yml,wmt14_en_de/validation_args.yml --hparams_set transformer_base --model_dir wmt14_en_de/benchmark_base
```

- training_args.yml
```yaml
entry.class: trainer
entry.params:
  train_steps: 200000
  summary_steps: 200
  save_checkpoint_steps: 1000
  criterion.class: label_smoothed_cross_entropy
  criterion.params:
    label_smoothing: 0.1
```
- translation_bpe.yml
```yaml

dataset.class: ParallelTextDataset
dataset.params:
  src_file: wmt14_en_de/train.en.tok.bpe.txt
  trg_file: wmt14_en_de/train.de.tok.bpe.txt
  data_is_processed: True

task.class: translation
task.params:
  batch_by_tokens: True
  batch_size: 4096
  max_src_len: 128
  max_trg_len: 128
  src_data_pipeline.class: TextDataPipeline
  src_data_pipeline.params:
    language: en
    tokenizer: moses
    subtokenizer: bpe
    subtokenizer_codes: wmt14_en_de/codes.bpe
    vocab_path: wmt14_en_de/vocab.en
  trg_data_pipeline.class: TextDataPipeline
  trg_data_pipeline.params:
    language: de
    tokenizer: moses
    subtokenizer: bpe
    subtokenizer_codes: wmt14_en_de/codes.bpe
    vocab_path: wmt14_en_de/vocab.de
```

- validation_args.yml
```yaml
validator.class: SeqGenerationValidator
validator.params:
  eval_dataset: ParallelTextDataset
  eval_dataset.params:
    src_file: wmt14_en_de/newstest2013.en.txt
    trg_file: wmt14_en_de/newstest2013.de.txt
  eval_batch_size: 64
  eval_start_at: 5000
  eval_steps: 1000
  eval_criterion: label_smoothed_cross_entropy
  eval_search_method: beam_search
  eval_search_method.params:
    beam_size: 4
    length_penalty: 0.6
    maximum_decode_length: 160
    extra_decode_length: 50
  eval_metric: bleu
  eval_top_checkpoints_to_keep: 10
  eval_auto_average_checkpoints: True
```
